version: '3'

services:
  database:
    image: mysql:5.7.27
    container_name: photogallery-db-prod
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'photogallery'
    volumes:
      # - ./waitForMySQL.sh:/docker-entrypoint-initdb.d/waitForMySQL.sh
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  photogallery:
    container_name: photogallery-prod
    build: .
    depends_on:
      - "database"
    ports:
      - "5000:5000"

  # seed:
  #   container_name: photogallery-seed
  #   build:
  #     context: .
  #   depends_on:
  #     - "database"
  #   ports:
  #     - "8001:8001"
