# FROM mysql:5.7.27
# ENV MYSQL_USER: 'root'
# ENV MYSQL_ROOT_PASSWORD: 'docker'
# ENV MYSQL_DATABASE: 'photogallery'
# COPY schema.sql /docker-entrypoint-initdb.d/schema.sql
# ADD waitForMySQL.sh .
# RUN chmod +x ./waitForMySQL.sh
# EXPOSE 3306